const fallbackCars = [
  {
    used_car_sku_id: 'car-001',
    model: 'Creta',
    oem: 'Hyundai',
    variant_name: 'SX Diesel AT',
    price: 1450000,
    formatted_price: '₹14.5 Lakh',
    image: 'https://images.unsplash.com/photo-1633789242441-8a4206346e56?w=600&h=400&fit=crop',
    year: 2022,
    km: '25000',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    city: 'Mumbai',
    locality: 'Andheri',
    owner: 1,
    mileage: 14,
    seating: 7,
    dailyRate: 2500,
    features: ['High Ground Clearance', 'Spacious Interior', 'AC', 'Power Steering', 'Modern Features'],
    purpose: 'Family Trip',
  },
  {
    used_car_sku_id: 'car-002',
    model: 'City',
    oem: 'Honda',
    variant_name: 'ZX CVT',
    price: 1200000,
    formatted_price: '₹12 Lakh',
    image: 'https://images.unsplash.com/photo-1606611013016-969c19ba27a5?w=600&h=400&fit=crop',
    year: 2021,
    km: '18000',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    city: 'Delhi',
    locality: 'Connaught Place',
    owner: 1,
    mileage: 16,
    seating: 5,
    dailyRate: 2000,
    features: ['Comfortable Ride', 'Large Boot Space', 'Petrol Engine', 'AC', 'Power Steering', 'Modern Features'],
    purpose: 'Office Work',
  },
  {
    used_car_sku_id: 'car-003',
    model: 'Swift',
    oem: 'Maruti',
    variant_name: 'ZXI Plus',
    price: 750000,
    formatted_price: '₹7.5 Lakh',
    image: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=600&h=400&fit=crop',
    year: 2020,
    km: '32000',
    fuelType: 'Petrol',
    transmission: 'Manual',
    bodyType: 'Hatchback',
    city: 'Bangalore',
    locality: 'Koramangala',
    owner: 2,
    mileage: 18,
    seating: 4,
    dailyRate: 1200,
    features: ['Easy Parking', 'Fuel Efficient', 'Petrol Engine', 'Manual Transmission', 'AC', 'Power Steering'],
    purpose: 'Solo Travel',
  },
  {
    used_car_sku_id: 'car-004',
    model: 'Nexon',
    oem: 'Tata',
    variant_name: 'XZ+ Dark Edition',
    price: 1100000,
    formatted_price: '₹11 Lakh',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=600&h=400&fit=crop',
    year: 2023,
    km: '12000',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'SUV',
    city: 'Pune',
    locality: 'Hinjewadi',
    owner: 1,
    mileage: 14,
    seating: 7,
    dailyRate: 2200,
    features: ['High Ground Clearance', 'Spacious Interior', 'Petrol Engine', 'AC', 'Power Steering', 'Modern Features'],
    purpose: 'Family Trip',
  },
  {
    used_car_sku_id: 'car-005',
    model: 'Verna',
    oem: 'Hyundai',
    variant_name: 'SX Turbo DCT',
    price: 1350000,
    formatted_price: '₹13.5 Lakh',
    image: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=600&h=400&fit=crop',
    year: 2022,
    km: '15000',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    city: 'Chennai',
    locality: 'T Nagar',
    owner: 1,
    mileage: 16,
    seating: 5,
    dailyRate: 2300,
    features: ['Comfortable Ride', 'Large Boot Space', 'Petrol Engine', 'AC', 'Power Steering', 'Modern Features'],
    purpose: 'Office Work',
  },
  {
    used_car_sku_id: 'car-006',
    model: 'i20',
    oem: 'Hyundai',
    variant_name: 'Asta',
    price: 850000,
    formatted_price: '₹8.5 Lakh',
    image: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=600&h=400&fit=crop',
    year: 2021,
    km: '22000',
    fuelType: 'Petrol',
    transmission: 'Manual',
    bodyType: 'Hatchback',
    city: 'Hyderabad',
    locality: 'Gachibowli',
    owner: 1,
    mileage: 18,
    seating: 4,
    dailyRate: 1400,
    features: ['Easy Parking', 'Fuel Efficient', 'Petrol Engine', 'Manual Transmission', 'AC', 'Power Steering', 'Modern Features'],
    purpose: 'Solo Travel',
  },
  {
    used_car_sku_id: 'car-007',
    model: 'XUV700',
    oem: 'Mahindra',
    variant_name: 'AX7',
    price: 1800000,
    formatted_price: '₹18 Lakh',
    image: 'https://images.unsplash.com/photo-1519641471654-76ce5427b9df?w=600&h=400&fit=crop',
    year: 2023,
    km: '8000',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    city: 'Mumbai',
    locality: 'Bandra',
    owner: 1,
    mileage: 14,
    seating: 7,
    dailyRate: 3500,
    features: ['High Ground Clearance', 'Spacious Interior', 'AC', 'Power Steering', 'Modern Features'],
    purpose: 'Family Trip',
  },
  {
    used_car_sku_id: 'car-008',
    model: 'Camry',
    oem: 'Toyota',
    variant_name: 'Hybrid',
    price: 3500000,
    formatted_price: '₹35 Lakh',
    image: 'https://images.unsplash.com/photo-1621007947388-bad3cc3955f7?w=600&h=400&fit=crop',
    year: 2022,
    km: '10000',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    city: 'Delhi',
    locality: 'South Extension',
    owner: 1,
    mileage: 16,
    seating: 5,
    dailyRate: 5000,
    features: ['Comfortable Ride', 'Large Boot Space', 'Petrol Engine', 'AC', 'Power Steering', 'Modern Features'],
    purpose: 'Office Work',
  },
  {
    used_car_sku_id: 'car-009',
    model: 'Baleno',
    oem: 'Maruti',
    variant_name: 'Alpha',
    price: 700000,
    formatted_price: '₹7 Lakh',
    image: 'https://images.unsplash.com/photo-148529157115f-772bc26599bb?w=600&h=400&fit=crop',
    year: 2019,
    km: '45000',
    fuelType: 'Petrol',
    transmission: 'Manual',
    bodyType: 'Hatchback',
    city: 'Jaipur',
    locality: 'Malviya Nagar',
    owner: 2,
    mileage: 18,
    seating: 4,
    dailyRate: 1000,
    features: ['Easy Parking', 'Fuel Efficient', 'Petrol Engine', 'Manual Transmission', 'AC', 'Power Steering'],
    purpose: 'Solo Travel',
  },
  {
    used_car_sku_id: 'car-010',
    model: 'Seltos',
    oem: 'Kia',
    variant_name: 'GTX+',
    price: 1550000,
    formatted_price: '₹15.5 Lakh',
    image: 'https://images.unsplash.com/photo-1679239872433-0d4a06e46e04?w=600&h=400&fit=crop',
    year: 2022,
    km: '20000',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    bodyType: 'SUV',
    city: 'Kolkata',
    locality: 'Salt Lake',
    owner: 1,
    mileage: 14,
    seating: 7,
    dailyRate: 2800,
    features: ['High Ground Clearance', 'Spacious Interior', 'AC', 'Power Steering', 'Modern Features'],
    purpose: 'Family Trip',
  },
  {
    used_car_sku_id: 'car-011',
    model: 'Amaze',
    oem: 'Honda',
    variant_name: 'VX CVT',
    price: 900000,
    formatted_price: '₹9 Lakh',
    image: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=600&h=400&fit=crop',
    year: 2020,
    km: '35000',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    city: 'Ahmedabad',
    locality: 'Satellite',
    owner: 2,
    mileage: 16,
    seating: 5,
    dailyRate: 1500,
    features: ['Comfortable Ride', 'Large Boot Space', 'Petrol Engine', 'AC', 'Power Steering'],
    purpose: 'Office Work',
  },
  {
    used_car_sku_id: 'car-012',
    model: 'Polo',
    oem: 'Volkswagen',
    variant_name: 'GT TSI',
    price: 950000,
    formatted_price: '₹9.5 Lakh',
    image: 'https://images.unsplash.com/photo-1542362567-b07e54358753?w=600&h=400&fit=crop',
    year: 2021,
    km: '28000',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    bodyType: 'Hatchback',
    city: 'Bangalore',
    locality: 'Indiranagar',
    owner: 1,
    mileage: 18,
    seating: 4,
    dailyRate: 1600,
    features: ['Easy Parking', 'Fuel Efficient', 'Petrol Engine', 'AC', 'Power Steering', 'Modern Features'],
    purpose: 'Solo Travel',
  },
];

export default fallbackCars;
